### ISSUE TITLE
Timer mit einstellbaren Suffix erstellen

### ISSUE THREAD

**Issue by MegaV0lt** [MarkusEh/vdr-plugin-tvscraper#1]
Wenn möglich bitte folgende Funktion einbauen:

Timer, die von TVScraper erstellt werden mit einem Suffix versehen, das einstellbar ist. Beispiel:
`The Walking Dead~Warlords  [TVScraper]` Mit zwei Leerzeichen

Aktueller Eintrag im Timer:
`1:S19.2E-1-1057-61205:2022-10-30:0215:0320:10:99:The Walking Dead~Warlords:<tvscraper><causedBy>The Walking Dead~Warlords  (S11E13)</causedBy><reason>improve</reason></tvscraper>
`
Eventuell mit dem Grund (CausedBy)

**Comment by MarkusEh** [comment]
Wird doch in vdr-plugin-live angezeit.
Sollen die Aufzeichnungen dann auch das Suffix bekommen?

**Comment by MegaV0lt** [comment]
Bei Live ja, Bei VDRAdmin nicht. Und am wichtigsten am VDR selbst. Der Timer bzw. die Aufnahme sollte das Suffix bekommen. Wie gesagt am besten einstellbar, falls jemand das nicht mag

**Comment by MarkusEh** [comment]
Kannst du mal --autoTimersPath ausprobieren? Siehe https://github.com/MarkusEh/vdr-plugin-tvscraper/wiki/Auto-Timers-to-Improve-and-Enhance-Existing-Recordings
Nicht exakt, was du willst. Aber ich möchte die Aufnahme nicht umbenennen. z.B. weil dann tvscraper Schwierigkeiten bekommt, die Aufnahme zu identifizieren

**Comment by MegaV0lt** [comment]
--autoTimerPath ist keine gute Lösung. Ich habe über 600 Aufnahmen auf der Platte und über 200 Suchtimer. Die sollten schon in das Originalverzeichnis

Warum verwendet TVScraper denn den Verzeichnisnamen zum Identifizieren der Aufnahme

Abfrage beim VDR oder aus der Info sollte doch zuverlässiger sein zumal bei den meisten die Sereien aufnehmen die Aufnahmen die SxxExx enthalten. Bei mir haben Serien auch das SxxExx angehängt.

Wenn beim TV-Scraper eine Option vorhanden wäre, die Aufnahmen/Timer mit einem Suffix zu versehen, dann wüsste TVScraper das doch.

Mach doch eine Option, die man in der Konfig einstellen muss:
```
--autotimerPrfix=
--autotimerSufficx=

```
Was auch noch toll wäre, ist wenn die SxxExx angehängt werden würden, so wie es epgSearch macht

**Comment by MarkusEh** [comment]
Hm, und dann will jemand nicht S3E6, sondern S03E006, oder (3/6), oder ...
Ich könnte ein Template machen, z.B.:
"Erster Teil S%.2sE%.3e, %t von tvscraper". Diesen String würde dann der Anwender erstellen, und tvscraper mitteilen. Am Besten über ein UI.
Tvscraper würde dann die % Teile entsprechend ersetzen, z.B. %t durch den Titel.

Und beim scrapen dann den Namen parsen, und herausfinden, wo das %t war. Und dann gibt es Probleme: Aufnahmen nicht von tvscraper, ohne diesen String. Der String wird geändert, und mit welchem String wurde jetzt der Dateiname erzeugt? ...

Überzeugt mich jetzt nicht. Metadaten sollten auch als Metadaten behandelt werden.
Mach doch mal einen thread im vdr-portal. Da können wir diskutieren, wie die Skins/live/vdradmin, ... solche Daten darstellen könnten.
