### ISSUE TITLE
Timer mit Unterverzeichniss

### ISSUE THREAD

**Issue by MegaV0lt** [MarkusEh/vdr-plugin-tvscraper#7]
Ich habe Aufnahmen von Serien mit manuell angelegten Unterverzeichnissen. Wenn TVScraper hier Timer anlegt, fehlen die Folgentitel

```
==> Von TVScraper angelegte Timer (2):
Chicago P.D.~S07~Chicago P.D.  [TVScraper] <- Chicago P.D.~S07~Blutopfer  (S07E06)
Chicago P.D.~S07~Chicago P.D.  [TVScraper] <- Chicago P.D.~S07~Die Seuche (Teil 3)  (S07E04)
```
Erste Spalte der angelegte Timer. Dahiner der Auslöser.

**Comment by MarkusEh** [comment]
Die Namen der Timer in [TVScraper] sind die Namen der Sendungen im EPG.
Bzw. der EPG Kurztext bei Serien.

**Comment by MegaV0lt** [comment]
Im EPG steht z.B. Blutopfer! Nur im Timer nicht. Der Timer wird so angelegt:
`Chicago P.D.~S07~Chicago P.D.`
Das liegt vermutlich am Unterverzeichniss S07
Richtig wäre
`Chicago P.D.~S07~Chicago P.D.~Blutopfer`

**Comment by MegaV0lt** [comment]
Hier mal so ein Timer

1:S9.0E-156-8700-20203:2023-12-13:2055:2200:15:99:Chicago P.D.~S07~Chicago P.D.:<tvscraper><causedBy>Chicago P.D.~S07~Die Seuche (Teil 3)  (S07E04)</causedBy><causedByIDs><eventID>7099944</eventID><eventStartTime>1696502100</eventStartTime><channelID>S9.0E-156-8700-20203</channelID></causedByIDs><reason>improve</reason></tvscraper><epgd><timerid>1431</timerid></epgd>


Am 10. Dezember 2023 09:46:30 MEZ schrieb Markus ***@***.***>:
>Die Namen der Timer in [TVScraper] sind die Namen der Sendungen im EPG.
>Bzw. der EPG Kurztext bei Serien.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/MarkusEh/vdr-plugin-tvscraper/issues/7#issuecomment-1848897857
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MarkusEh** [comment]
Fixed in git
